
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class addStudent extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public addStudent() {
        super("Add Student");
        initComponents();
        
        conn = databaseConnection.connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        studentID = new javax.swing.JLabel();
        nameStudent = new javax.swing.JLabel();
        facultyStudent = new javax.swing.JLabel();
        yearLevel = new javax.swing.JLabel();
        locationStudent = new javax.swing.JLabel();
        acadCareer = new javax.swing.JLabel();
        gradStat = new javax.swing.JLabel();
        empStat = new javax.swing.JLabel();
        Citizenship = new javax.swing.JLabel();
        Religion = new javax.swing.JLabel();
        sexStudent = new javax.swing.JLabel();
        civilStat = new javax.swing.JLabel();
        currResidence = new javax.swing.JLabel();
        currTelNum = new javax.swing.JLabel();
        currEmailAdd = new javax.swing.JLabel();
        student_num = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        enrollmentButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        studentList = new javax.swing.JButton();
        current_tel_num = new javax.swing.JTextField();
        current_email_address = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        religion = new javax.swing.JTextField();
        citizenship = new javax.swing.JTextField();
        current_residence = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        employment_status = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        academic_career = new javax.swing.JComboBox<>();
        graduating_status = new javax.swing.JComboBox<>();
        backAdd = new javax.swing.JButton();
        submitAdd = new javax.swing.JButton();
        year_level = new javax.swing.JTextField();
        sex_at_birth = new javax.swing.JComboBox<>();
        civil_status = new javax.swing.JComboBox<>();
        faculty = new javax.swing.JComboBox<>();
        location = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileStudent = new javax.swing.JMenu();
        homeStudent = new javax.swing.JMenuItem();
        logoutStudent = new javax.swing.JMenuItem();
        editStudent = new javax.swing.JMenu();
        aboutUsStudent = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        studentID.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        studentID.setText("Student Number");

        nameStudent.setText("Name");

        facultyStudent.setText("Faculty");

        yearLevel.setText("Year Level");

        locationStudent.setText("Location");

        acadCareer.setText("Academic Career");

        gradStat.setText("Graduating Status");

        empStat.setText("Employment Status");

        Citizenship.setText("Citizenship");

        Religion.setText("Religion");

        sexStudent.setText("Sex");

        civilStat.setText("Civil Status");

        currResidence.setText("Current Residence");

        currTelNum.setText("Current Tel. Num");

        currEmailAdd.setText("Current Email Address");

        student_num.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        student_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_numActionPerformed(evt);
            }
        });

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(144, 20, 52));

        jLabel1.setFont(new java.awt.Font("Tiro Bangla", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student Registration Details");

        enrollmentButton.setBackground(new java.awt.Color(10, 128, 69));
        enrollmentButton.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        enrollmentButton.setForeground(new java.awt.Color(255, 255, 255));
        enrollmentButton.setText("+   STUDENT ENROLLMENT");
        enrollmentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollmentButtonActionPerformed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon("/Users/e./Downloads/University_of_The_Philippines-2.png")); // NOI18N

        studentList.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        studentList.setText("STUDENT LIST");
        studentList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(447, 447, 447)
                .addComponent(enrollmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentList, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(14, 14, 14))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enrollmentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentList, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel3.setText("Personal Information");

        citizenship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                citizenshipActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel4.setText("Contact Information");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("University Details");

        academic_career.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "U", "G", "C", "ND", "CE", " " }));

        graduating_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));

        backAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        backAdd.setText("BACK");
        backAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backAddActionPerformed(evt);
            }
        });

        submitAdd.setBackground(new java.awt.Color(27, 133, 253));
        submitAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        submitAdd.setForeground(new java.awt.Color(255, 255, 255));
        submitAdd.setText("SAVE STUDENT DETAILS");
        submitAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAddActionPerformed(evt);
            }
        });

        sex_at_birth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));

        civil_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "SE", "D", "W" }));

        faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FICS", "FEd", "FMDS" }));

        location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local", "Offshore" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(empStat)
                    .addComponent(currResidence)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(studentID, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nameStudent, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(Citizenship)
                    .addComponent(civilStat)
                    .addComponent(Religion)
                    .addComponent(sexStudent))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(employment_status, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(current_residence, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(citizenship, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(student_num, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(religion, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sex_at_birth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(civil_status, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(currTelNum)
                            .addComponent(jLabel4)
                            .addComponent(currEmailAdd)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2))
                                .addComponent(yearLevel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(facultyStudent)
                                    .addComponent(locationStudent))
                                .addComponent(acadCareer, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(gradStat, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(year_level)
                            .addComponent(faculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(location, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(submitAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(current_tel_num)
                            .addComponent(current_email_address)
                            .addComponent(academic_career, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(graduating_status, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentID)
                            .addComponent(student_num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameStudent))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexStudent)
                            .addComponent(sex_at_birth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(civilStat)
                            .addComponent(civil_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Religion)
                            .addComponent(religion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Citizenship)
                            .addComponent(citizenship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currResidence)
                            .addComponent(current_residence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(empStat)
                            .addComponent(employment_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currTelNum)
                            .addComponent(current_tel_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currEmailAdd)
                            .addComponent(current_email_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearLevel)
                            .addComponent(year_level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(facultyStudent)
                            .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(locationStudent)
                            .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acadCareer)
                            .addComponent(academic_career, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gradStat)
                            .addComponent(graduating_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        fileStudent.setText("File");

        homeStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        homeStudent.setText("Home");
        homeStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeStudentActionPerformed(evt);
            }
        });
        fileStudent.add(homeStudent);

        logoutStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logoutStudent.setText("Logout");
        logoutStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutStudentActionPerformed(evt);
            }
        });
        fileStudent.add(logoutStudent);

        jMenuBar1.add(fileStudent);

        editStudent.setText("About");

        aboutUsStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        aboutUsStudent.setText("About Us");
        aboutUsStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsStudentActionPerformed(evt);
            }
        });
        editStudent.add(aboutUsStudent);

        jMenuBar1.add(editStudent);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1379, 897));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_homeStudentActionPerformed

    private void logoutStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login object = new login();
        object.setVisible(true);
    }//GEN-LAST:event_logoutStudentActionPerformed

    private void student_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_numActionPerformed

    private void submitAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitAddActionPerformed
        // submit button
        try {
            stmt = conn.createStatement();
            
            // get text in the textfield and store in local variable
            // string
            String std_name = name.getText();
            String std_religion = religion.getText();
            String std_employment_status = employment_status.getText();
            String std_citizenship = citizenship.getText();
            String std_current_residence = current_residence.getText();
            String std_current_tel_num = current_tel_num.getText();
            String std_current_email_address = current_email_address.getText();

            // combobox na string 
            String std_sex_at_birth = (String) sex_at_birth.getSelectedItem(); // combobox
            String std_civil_status = (String) civil_status.getSelectedItem();
            String std_faculty = (String) faculty.getSelectedItem();
            String std_location = (String) location.getSelectedItem();
            String std_academic_career = (String) academic_career.getSelectedItem();
            String std_graduating_status = (String) graduating_status.getSelectedItem();
            
            // int
            int std_student_num = Integer.parseInt(student_num.getText()); // convert string to int if hindi combobox
            int std_year_level = Integer.parseInt(year_level.getText());
                   
                     
            // string for INSERT slq query, var name sa db then var name sa code/program
            String sql = "INSERT INTO student_info" 
                    + "(academic_career,citizenship,civil_status,current_email_address,current_residence,"
                    + "current_tel_num,employment_status,faculty,graduating_status,location,name,"
                    + "religion,sex_at_birth,year_level,student_num) "
                    + "VALUES  ('"+std_academic_career+"', '"+std_citizenship+"', '"+std_civil_status+"', '"+std_current_email_address+"', '"+std_current_residence+"', "
                    + "'"+std_current_tel_num+"', '"+std_employment_status+"', '"+std_faculty+"', '"+std_graduating_status+"', '"+std_location+"', "
                    + "'"+std_name+"', '"+std_religion+"', '"+std_sex_at_birth+"', '"+std_year_level+"', '"+std_student_num+"')";
            
            // execute query
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Student data is successfully added!");
            
           
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
  
    }//GEN-LAST:event_submitAddActionPerformed

    private void backAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backAddActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_backAddActionPerformed

    private void aboutUsStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        aboutUS object = new aboutUS();
        object.setVisible(true);
    }//GEN-LAST:event_aboutUsStudentActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void citizenshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_citizenshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_citizenshipActionPerformed

    private void enrollmentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollmentButtonActionPerformed
        // TODO add your handling code here:
        // enrollment
        setVisible(false);
        enrollment object = new enrollment();
        object.setVisible(true);
    }//GEN-LAST:event_enrollmentButtonActionPerformed

    private void studentListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentListActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        showStudent object = new showStudent();
        object.setVisible(true);
    }//GEN-LAST:event_studentListActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Citizenship;
    private javax.swing.JLabel Religion;
    private javax.swing.JMenuItem aboutUsStudent;
    private javax.swing.JLabel acadCareer;
    private javax.swing.JComboBox<String> academic_career;
    private javax.swing.JButton backAdd;
    private javax.swing.JTextField citizenship;
    private javax.swing.JLabel civilStat;
    private javax.swing.JComboBox<String> civil_status;
    private javax.swing.JLabel currEmailAdd;
    private javax.swing.JLabel currResidence;
    private javax.swing.JLabel currTelNum;
    private javax.swing.JTextField current_email_address;
    private javax.swing.JTextField current_residence;
    private javax.swing.JTextField current_tel_num;
    private javax.swing.JMenu editStudent;
    private javax.swing.JLabel empStat;
    private javax.swing.JTextField employment_status;
    private javax.swing.JButton enrollmentButton;
    private javax.swing.JComboBox<String> faculty;
    private javax.swing.JLabel facultyStudent;
    private javax.swing.JMenu fileStudent;
    private javax.swing.JLabel gradStat;
    private javax.swing.JComboBox<String> graduating_status;
    private javax.swing.JMenuItem homeStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JComboBox<String> location;
    private javax.swing.JLabel locationStudent;
    private javax.swing.JMenuItem logoutStudent;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameStudent;
    private javax.swing.JTextField religion;
    private javax.swing.JLabel sexStudent;
    private javax.swing.JComboBox<String> sex_at_birth;
    private javax.swing.JLabel studentID;
    private javax.swing.JButton studentList;
    private javax.swing.JTextField student_num;
    private javax.swing.JButton submitAdd;
    private javax.swing.JLabel yearLevel;
    private javax.swing.JTextField year_level;
    // End of variables declaration//GEN-END:variables
}
