
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;


public class course extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public course() {
        super("Course Records"); 
        initComponents();
        
        conn = databaseConnection.connection(); // db connection
        
        courseRecords(); 
    }
    
    public void courseRecords() {
        
        // create try catch for db connection
        try {
            stmt = conn.createStatement();
            String sql = "SELECT * FROM course_info";
            ResultSet res = stmt.executeQuery(sql);
            jTable2.setModel(DbUtils.resultSetToTableModel(res));
                    
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        fileStudent1 = new javax.swing.JMenu();
        homeStudent1 = new javax.swing.JMenuItem();
        logoutStudent1 = new javax.swing.JMenuItem();
        editStudent1 = new javax.swing.JMenu();
        aboutUsStudent1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        course_code = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        course_name = new javax.swing.JTextField();
        unit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        AdCourse = new javax.swing.JButton();
        updateCourse = new javax.swing.JButton();
        deleteCourse = new javax.swing.JButton();
        searchMe = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        backCourse = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar3 = new javax.swing.JMenuBar();
        fileStudent2 = new javax.swing.JMenu();
        homeStudent2 = new javax.swing.JMenuItem();
        logoutStudent2 = new javax.swing.JMenuItem();
        editStudent2 = new javax.swing.JMenu();
        aboutUsStudent2 = new javax.swing.JMenuItem();

        jMenuBar2.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar2.setForeground(new java.awt.Color(255, 255, 255));

        fileStudent1.setText("File");

        homeStudent1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        homeStudent1.setText("Home");
        homeStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeStudent1ActionPerformed(evt);
            }
        });
        fileStudent1.add(homeStudent1);

        logoutStudent1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logoutStudent1.setText("Logout");
        logoutStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutStudent1ActionPerformed(evt);
            }
        });
        fileStudent1.add(logoutStudent1);

        jMenuBar2.add(fileStudent1);

        editStudent1.setText("About");

        aboutUsStudent1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        aboutUsStudent1.setText("About Us");
        aboutUsStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsStudent1ActionPerformed(evt);
            }
        });
        editStudent1.add(aboutUsStudent1);

        jMenuBar2.add(editStudent1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Course Information");

        jLabel2.setText("Course Code");

        course_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_codeActionPerformed(evt);
            }
        });

        jLabel3.setText("Course Name");

        course_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_nameActionPerformed(evt);
            }
        });

        unit.setVerifyInputWhenFocusTarget(false);

        jLabel4.setText("Unit");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Course Code", "Course Name", "Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable2);

        AdCourse.setBackground(new java.awt.Color(10, 128, 69));
        AdCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        AdCourse.setForeground(new java.awt.Color(255, 255, 255));
        AdCourse.setText("ADD");
        AdCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdCourseActionPerformed(evt);
            }
        });

        updateCourse.setBackground(new java.awt.Color(27, 133, 253));
        updateCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updateCourse.setForeground(new java.awt.Color(255, 255, 255));
        updateCourse.setText("UPDATE");
        updateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateCourseActionPerformed(evt);
            }
        });

        deleteCourse.setBackground(new java.awt.Color(255, 0, 0));
        deleteCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        deleteCourse.setForeground(new java.awt.Color(255, 255, 255));
        deleteCourse.setText("DELETE");
        deleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCourseActionPerformed(evt);
            }
        });

        searchMe.setBackground(new java.awt.Color(253, 248, 225));
        searchMe.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        searchMe.setText("SEARCH");
        searchMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchMeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(course_name, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(course_code, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchMe, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(searchMe, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course_code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(unit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AdCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deleteCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(144, 20, 52));

        backCourse.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        backCourse.setText("BACK");
        backCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backCourseActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon("/Users/e./Downloads/University_of_The_Philippines-2.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tiro Bangla", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Registration Details");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(14, 14, 14))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar3.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar3.setForeground(new java.awt.Color(255, 255, 255));

        fileStudent2.setText("File");

        homeStudent2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        homeStudent2.setText("Home");
        homeStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeStudent2ActionPerformed(evt);
            }
        });
        fileStudent2.add(homeStudent2);

        logoutStudent2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logoutStudent2.setText("Logout");
        logoutStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutStudent2ActionPerformed(evt);
            }
        });
        fileStudent2.add(logoutStudent2);

        jMenuBar3.add(fileStudent2);

        editStudent2.setText("About");

        aboutUsStudent2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        aboutUsStudent2.setText("About Us");
        aboutUsStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsStudent2ActionPerformed(evt);
            }
        });
        editStudent2.add(aboutUsStudent2);

        jMenuBar3.add(editStudent2);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1346, 896));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeStudent1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_homeStudent1ActionPerformed

    private void logoutStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutStudent1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login object = new login();
        object.setVisible(true);
    }//GEN-LAST:event_logoutStudent1ActionPerformed

    private void aboutUsStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsStudent1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        aboutUS object = new aboutUS();
        object.setVisible(true);
    }//GEN-LAST:event_aboutUsStudent1ActionPerformed

    private void homeStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeStudent2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_homeStudent2ActionPerformed

    private void logoutStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutStudent2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login object = new login();
        object.setVisible(true);
    }//GEN-LAST:event_logoutStudent2ActionPerformed

    private void aboutUsStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsStudent2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        aboutUS object = new aboutUS();
        object.setVisible(true);
    }//GEN-LAST:event_aboutUsStudent2ActionPerformed

    private void backCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backCourseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_backCourseActionPerformed

    private void AdCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdCourseActionPerformed
        // TODO add your handling code here:
        try {
            stmt = conn.createStatement();
            
            // get text in the textfield and store in local variable
            // string
            String course_courseCode = course_code.getText();
            String course_courseName = course_name.getText();
            String course_courseUnit = unit.getText();
            
            // int
                   
                     
            // string for INSERT slq query, var name sa db then var name sa code/program
            String sql = "INSERT INTO course_info"
                    + "(course_code,course_name,unit)"
                    + "VALUES  ('"+course_courseCode+"', '"+course_courseName+"', '"+course_courseUnit+"')";
            
            // execute query
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Student data is successfully added!");
            
            setVisible(false);
            course object = new course();
            object.setVisible(true);
            
           
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_AdCourseActionPerformed

    private void course_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_nameActionPerformed

    private void course_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_course_codeActionPerformed

    private void updateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateCourseActionPerformed
        // TODO add your handling code here:
        try {
            stmt = conn.createStatement();
            
            // get text in the textfield and store in local variable
            // string
            String course_courseCode = course_code.getText();
            String course_courseName = course_name.getText();
            String course_courseUnit = unit.getText();
            int newCourseUnit = Integer.parseInt(course_courseUnit);
            
            
            // int
                   
                     
            // string for INSERT slq query, var name sa db then var name sa code/program
            String sql = "UPDATE course_info SET "
            + "course_name = '" + course_courseName + "', "
            + "unit = " + newCourseUnit + " " // No single quotes around newCourseUnit
            + "WHERE course_code = '" + course_courseCode + "'"; // Use single quotes if course_code is a string, otherwise remove them if it is an integer

            
            // execute query
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Student data is successfully added!");
            
            setVisible(false);
            course object = new course();
            object.setVisible(true);
            
           
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateCourseActionPerformed

    private void deleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCourseActionPerformed
        // TODO add your handling code here:
        try{
        // DELETE FUNCTION
            stmt = conn.createStatement(); 
            
            String course_courseCode = course_code.getText(); 
            
            String sql = "DELETE FROM course_info WHERE course_code = '"+course_courseCode+"' ";
            stmt.executeUpdate(sql);
            
            setVisible(false);
            course object = new course();
            object.setVisible(true);
           
            }catch(NumberFormatException | SQLException e) { 
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_deleteCourseActionPerformed

    private void searchMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchMeActionPerformed
        // TODO add your handling code here:
                                                    
        // TODO add your hßandling code here:

        try {
            stmt = conn.createStatement();

            String course_courseCode = course_code.getText(); 
            //int course_courseCode = Integer.parseInt(course_code.getText());
            String sql = "SELECT * FROM course_info WHERE course_code = '"+course_courseCode+"' ";

            // store the fetched student record to rs variable
            rs = stmt.executeQuery(sql);
            course_code.removeAll();

            if (rs.next()) {
                // do this for all the attributes
                // string
                course_code.setText(rs.getString("course_code"));
                course_name.setText(rs.getString("course_name"));
                unit.setText(rs.getString("unit"));

            } else {
                JOptionPane.showMessageDialog(null, "Record not found");
            }

        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }                                      

    }//GEN-LAST:event_searchMeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdCourse;
    private javax.swing.JMenuItem aboutUsStudent1;
    private javax.swing.JMenuItem aboutUsStudent2;
    private javax.swing.JButton backCourse;
    private javax.swing.JTextField course_code;
    private javax.swing.JTextField course_name;
    private javax.swing.JButton deleteCourse;
    private javax.swing.JMenu editStudent1;
    private javax.swing.JMenu editStudent2;
    private javax.swing.JMenu fileStudent1;
    private javax.swing.JMenu fileStudent2;
    private javax.swing.JMenuItem homeStudent1;
    private javax.swing.JMenuItem homeStudent2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JMenuItem logoutStudent1;
    private javax.swing.JMenuItem logoutStudent2;
    private javax.swing.JButton searchMe;
    private javax.swing.JTextField unit;
    private javax.swing.JButton updateCourse;
    // End of variables declaration//GEN-END:variables
}
