
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

import java.util.ArrayList;
import java.util.List;

public class enrollment extends javax.swing.JFrame {

    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    
    public enrollment() {
        super("Course Enrollment"); // act as title ng frame
        initComponents();
        
        conn = databaseConnection.connection(); // db connection
        
        // call the function to show records sa tale
        courseRecords();
   
    }
    
    public void courseRecords() {
        
        // create try catch for db connection
        try {
            stmt = conn.createStatement();
            String sql = "SELECT * FROM enrollment";
            ResultSet res = stmt.executeQuery(sql);
            enrollmentTable.setModel(DbUtils.resultSetToTableModel(res));
                    
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
            
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        enrollment_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        academic_year = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        course_code = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        term = new javax.swing.JTextField();
        student_num = new javax.swing.JTextField();
        addEnrollment = new javax.swing.JButton();
        updateEnrollment = new javax.swing.JButton();
        deleteEnrollment = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        enrollmentTable = new javax.swing.JTable();
        course_code1 = new javax.swing.JTextField();
        course_code2 = new javax.swing.JTextField();
        course_code3 = new javax.swing.JTextField();
        course_code4 = new javax.swing.JTextField();
        course_code5 = new javax.swing.JTextField();
        course_code6 = new javax.swing.JTextField();
        course_code7 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        addPayment = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backCourse1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        searchEnrollment = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        fileStudent2 = new javax.swing.JMenu();
        homeStudent2 = new javax.swing.JMenuItem();
        logoutStudent2 = new javax.swing.JMenuItem();
        editStudent2 = new javax.swing.JMenu();
        aboutUsStudent2 = new javax.swing.JMenuItem();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Course Information");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel2.setText("Enrollment Information");

        jLabel3.setText("Enrollment ID");

        enrollment_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enrollment_idActionPerformed(evt);
            }
        });

        jLabel4.setText("Academic Year");

        jLabel6.setText("Course Code");

        jLabel8.setText("Student Number");

        jLabel9.setText("Term");

        term.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                termActionPerformed(evt);
            }
        });

        student_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                student_numActionPerformed(evt);
            }
        });

        addEnrollment.setBackground(new java.awt.Color(10, 128, 69));
        addEnrollment.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addEnrollment.setForeground(new java.awt.Color(255, 255, 255));
        addEnrollment.setText("ADD");
        addEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnrollmentActionPerformed(evt);
            }
        });

        updateEnrollment.setBackground(new java.awt.Color(27, 133, 253));
        updateEnrollment.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        updateEnrollment.setForeground(new java.awt.Color(255, 255, 255));
        updateEnrollment.setText("UPDATE");
        updateEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEnrollmentActionPerformed(evt);
            }
        });

        deleteEnrollment.setBackground(new java.awt.Color(255, 0, 0));
        deleteEnrollment.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        deleteEnrollment.setForeground(new java.awt.Color(255, 255, 255));
        deleteEnrollment.setText("DELETE");
        deleteEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEnrollmentActionPerformed(evt);
            }
        });

        enrollmentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Enrollement ID", "Academc Year", "Course Code", "Term", "Unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        enrollmentTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(enrollmentTable);
        if (enrollmentTable.getColumnModel().getColumnCount() > 0) {
            enrollmentTable.getColumnModel().getColumn(1).setPreferredWidth(20);
            enrollmentTable.getColumnModel().getColumn(2).setPreferredWidth(10);
            enrollmentTable.getColumnModel().getColumn(3).setPreferredWidth(5);
            enrollmentTable.getColumnModel().getColumn(4).setPreferredWidth(5);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(student_num, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(29, 29, 29)
                        .addComponent(course_code, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(term, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(academic_year, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(updateEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(29, 29, 29)
                        .addComponent(enrollment_id, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(course_code1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_code2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_code4, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_code3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_code6, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_code5, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_code7, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(enrollment_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(student_num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(course_code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(course_code2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(course_code1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(course_code3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(course_code4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(course_code5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(course_code6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(course_code7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(academic_year, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(term, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 828, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(144, 20, 52));

        addPayment.setBackground(new java.awt.Color(10, 128, 69));
        addPayment.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        addPayment.setForeground(new java.awt.Color(255, 255, 255));
        addPayment.setText("ADD PAYMENT");
        addPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaymentActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon("/Users/e./Downloads/University_of_The_Philippines-2.png")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tiro Bangla", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Registration Details");

        backCourse1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        backCourse1.setText("BACK");
        backCourse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backCourse1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        searchEnrollment.setBackground(new java.awt.Color(253, 248, 225));
        searchEnrollment.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        searchEnrollment.setText("SEARCH");
        searchEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEnrollmentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(149, 149, 149)
                .addComponent(jTextField1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125)
                .addComponent(addPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(14, 14, 14))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(addPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backCourse1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchEnrollment, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar3.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar3.setForeground(new java.awt.Color(255, 255, 255));

        fileStudent2.setText("File");

        homeStudent2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        homeStudent2.setText("Home");
        homeStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeStudent2ActionPerformed(evt);
            }
        });
        fileStudent2.add(homeStudent2);

        logoutStudent2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logoutStudent2.setText("Logout");
        logoutStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutStudent2ActionPerformed(evt);
            }
        });
        fileStudent2.add(logoutStudent2);

        jMenuBar3.add(fileStudent2);

        editStudent2.setText("About");

        aboutUsStudent2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        aboutUsStudent2.setText("About Us");
        aboutUsStudent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsStudent2ActionPerformed(evt);
            }
        });
        editStudent2.add(aboutUsStudent2);

        jMenuBar3.add(editStudent2);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1346, 989));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeStudent2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_homeStudent2ActionPerformed

    private void logoutStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutStudent2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login object = new login();
        object.setVisible(true);
    }//GEN-LAST:event_logoutStudent2ActionPerformed

    private void aboutUsStudent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsStudent2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        enrollment object = new enrollment();
        object.setVisible(true);
    }//GEN-LAST:event_aboutUsStudent2ActionPerformed

    private void deleteEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEnrollmentActionPerformed
        // TODO add your handling code here:
        try{
        // DELETE FUNCTION
            stmt = conn.createStatement(); 
            
            String enrollment_enrollment_id = enrollment_id.getText(); 
            
            String sql = "DELETE FROM enrollment WHERE enrollment_id = '"+enrollment_enrollment_id+"' ";
            stmt.executeUpdate(sql);
            
            setVisible(false);
            enrollment object = new enrollment();
            object.setVisible(true);
           
            }catch(NumberFormatException | SQLException e) { 
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_deleteEnrollmentActionPerformed

    private void updateEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEnrollmentActionPerformed
        // TODO add your handling code here:
         try {
            stmt = conn.createStatement();
            
            // get text in the textfield and store in local variable
            // string
            String enrollment_enrollment_id = enrollment_id.getText();
            String enrollment_student_num = student_num.getText();
            String enrollment_course_code = course_code.getText();
            String enrollment_academic_year = academic_year.getText();
            String enrollment_term = term.getText();
            int newTerm = Integer.parseInt(enrollment_term);
            
            
            // int
                   
                     
            // string for INSERT slq query, var name sa db then var name sa code/program
            String sql = "UPDATE enrollment SET "
            + "academic_year = '" + enrollment_academic_year + "', "
            + "course_code = '" + enrollment_course_code + "', "
            + "student_num = '" + enrollment_student_num + "', "
            + "term = " + newTerm + " " // No single quotes around newCourseUnit
            + "WHERE enrollment_id = '" + enrollment_enrollment_id + "'"; // Use single quotes if course_code is a string, otherwise remove them if it is an integer

            
            // execute query
            stmt.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Enrollment data is successfully updated!");
            
            setVisible(false);
            course object = new course();
            object.setVisible(true);
            
           
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_updateEnrollmentActionPerformed

    private void searchEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEnrollmentActionPerformed
        // TODO add your handling code here:
        try {
            stmt = conn.createStatement();

            String enrollment_enrollment_id = enrollment_id.getText(); 
            //int course_courseCode = Integer.parseInt(course_code.getText());
            String sql = "SELECT * FROM enrollment WHERE enrollment_id = '"+enrollment_enrollment_id+"' ";

            // store the fetched student record to rs variable
            rs = stmt.executeQuery(sql);
            enrollment_id.removeAll();

            if (rs.next()) {
                // do this for all the attributes
                // string
                enrollment_id.setText(rs.getString("enrollment_id"));
                academic_year.setText(rs.getString("academic_year"));
                course_code.setText(rs.getString("course_code"));
                student_num.setText(rs.getString("student_num"));
                term.setText(rs.getString("term"));

            } else {
                JOptionPane.showMessageDialog(null, "Record not found");
            }

        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }                                      

    }//GEN-LAST:event_searchEnrollmentActionPerformed

    private void addEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnrollmentActionPerformed

        // add enrollment w/ multiple courses
        // add enrollment w/ multiple course
        
        int enrollmentId = 1;
        String currentAcademicYear = "";
        String currentTerm = "";
        String currentStudentNum = "";
        List<Course> courses = new ArrayList<>();
        courses.add(new Course(course_code.getText(), 3, 1, academic_year.getText(), student_num.getText(), enrollmentId));
        courses.add(new Course(course_code1.getText(), 3, 1, academic_year.getText(), student_num.getText(), enrollmentId));
        courses.add(new Course(course_code2.getText(), 3, 1, academic_year.getText(), student_num.getText(), enrollmentId));
        courses.add(new Course(course_code3.getText(), 3, 1, academic_year.getText(), student_num.getText(), enrollmentId));
        courses.add(new Course(course_code4.getText(), 3, 1, academic_year.getText(), student_num.getText(), enrollmentId));
        courses.add(new Course(course_code5.getText(), 3, 1, academic_year.getText(), student_num.getText(), enrollmentId));
        courses.add(new Course(course_code6.getText(), 3, 1, academic_year.getText(), student_num.getText(), enrollmentId));
        courses.add(new Course(course_code7.getText(), 3, 1, academic_year.getText(), student_num.getText(), enrollmentId));

        for (Course course : courses) {
            if (!course.getAcademicYear().equals(currentAcademicYear) || !course.getTerm().equals(currentTerm) || !course.getStudentNum().equals(currentStudentNum)) {
                enrollmentId++;
                currentAcademicYear = course.getAcademicYear();
                currentTerm = course.getTerm();
                currentStudentNum = course.getStudentNum();
            }
            course.setEnrollmentId(enrollmentId);
        }

        try {
            stmt = conn.createStatement();
            for (Course course : courses) {
                String sql = "INSERT INTO enrollment (enrollment_id, academic_year, course_code, student_num, term) VALUES ("
                        + course.getEnrollmentId() + ", '"
                        + course.getAcademicYear() + "', '"
                        + course.getCourseCode() + "', '"
                        + course.getStudentNum() + "', "
                        + course.getTerm() + ")";
                stmt.executeUpdate(sql);
            }
            JOptionPane.showMessageDialog(null, "Enrollment data is successfully added!");

            setVisible(false);
            enrollment object = new enrollment();
            object.setVisible(true);

        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }             
    }//GEN-LAST:event_addEnrollmentActionPerformed

    private void enrollment_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enrollment_idActionPerformed
        // TODO add your handling code here:
        enrollment_id.setEditable(false);
        
    }//GEN-LAST:event_enrollment_idActionPerformed

    private void addPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaymentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        payment object = new payment();
        object.setVisible(true);
    }//GEN-LAST:event_addPaymentActionPerformed

    private void backCourse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backCourse1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        addStudent object = new addStudent();
        object.setVisible(true);
    }//GEN-LAST:event_backCourse1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void termActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_termActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_termActionPerformed

    private void student_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_student_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_student_numActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enrollment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enrollment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutUsStudent2;
    private javax.swing.JTextField academic_year;
    private javax.swing.JButton addEnrollment;
    private javax.swing.JButton addPayment;
    private javax.swing.JButton backCourse1;
    private javax.swing.JTextField course_code;
    private javax.swing.JTextField course_code1;
    private javax.swing.JTextField course_code2;
    private javax.swing.JTextField course_code3;
    private javax.swing.JTextField course_code4;
    private javax.swing.JTextField course_code5;
    private javax.swing.JTextField course_code6;
    private javax.swing.JTextField course_code7;
    private javax.swing.JButton deleteEnrollment;
    private javax.swing.JMenu editStudent2;
    private javax.swing.JTable enrollmentTable;
    private javax.swing.JTextField enrollment_id;
    private javax.swing.JMenu fileStudent2;
    private javax.swing.JMenuItem homeStudent2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem logoutStudent2;
    private javax.swing.JButton searchEnrollment;
    private javax.swing.JTextField student_num;
    private javax.swing.JTextField term;
    private javax.swing.JButton updateEnrollment;
    // End of variables declaration//GEN-END:variables
}
