
// import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

public class showStudent extends javax.swing.JFrame {

    /**
     * Creates new form showStudent
     */
    
    Connection conn = null;
    Statement stmt = null;
    ResultSet rs = null;
    
    public showStudent() {
        super("Student Records"); // act as title ng frame
        initComponents();
        
        conn = databaseConnection.connection(); // db connection
        
        // call the function to show records sa tale
        showRecords();
        
    }
    
    public void showRecords() {
        
        // create try catch for db connection
        try {
            stmt = conn.createStatement();
            String sql = "SELECT * FROM student_info";
            ResultSet res = stmt.executeQuery(sql);
            jTable1.setModel(DbUtils.resultSetToTableModel(res));
                    
        } catch(SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        fileStudent = new javax.swing.JMenu();
        homeStudent = new javax.swing.JMenuItem();
        logoutStudent = new javax.swing.JMenuItem();
        editStudent = new javax.swing.JMenu();
        aboutUsStudent = new javax.swing.JMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        backShow = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        fileStudent1 = new javax.swing.JMenu();
        homeStudent1 = new javax.swing.JMenuItem();
        logoutStudent1 = new javax.swing.JMenuItem();
        editStudent1 = new javax.swing.JMenu();
        aboutUsStudent1 = new javax.swing.JMenuItem();

        jMenuBar1.setBackground(new java.awt.Color(102, 102, 102));
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        fileStudent.setText("File");

        homeStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        homeStudent.setText("Home");
        homeStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeStudentActionPerformed(evt);
            }
        });
        fileStudent.add(homeStudent);

        logoutStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logoutStudent.setText("Logout");
        logoutStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutStudentActionPerformed(evt);
            }
        });
        fileStudent.add(logoutStudent);

        jMenuBar1.add(fileStudent);

        editStudent.setText("About");

        aboutUsStudent.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        aboutUsStudent.setText("About Us");
        aboutUsStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsStudentActionPerformed(evt);
            }
        });
        editStudent.add(aboutUsStudent);

        jMenuBar1.add(editStudent);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(144, 20, 52));

        jLabel5.setFont(new java.awt.Font("Tiro Bangla", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Student Registration Details");

        backShow.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        backShow.setText("BACK");
        backShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backShowActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon("/Users/e./Downloads/University_of_The_Philippines-2.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel20)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 942, Short.MAX_VALUE)
                .addComponent(backShow, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(backShow, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel20)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jMenuBar2.setBackground(new java.awt.Color(51, 51, 51));
        jMenuBar2.setForeground(new java.awt.Color(255, 255, 255));

        fileStudent1.setText("File");

        homeStudent1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        homeStudent1.setText("Home");
        homeStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeStudent1ActionPerformed(evt);
            }
        });
        fileStudent1.add(homeStudent1);

        logoutStudent1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        logoutStudent1.setText("Logout");
        logoutStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutStudent1ActionPerformed(evt);
            }
        });
        fileStudent1.add(logoutStudent1);

        jMenuBar2.add(fileStudent1);

        editStudent1.setText("About");

        aboutUsStudent1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        aboutUsStudent1.setText("About Us");
        aboutUsStudent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutUsStudent1ActionPerformed(evt);
            }
        });
        editStudent1.add(aboutUsStudent1);

        jMenuBar2.add(editStudent1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1589, 913));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_homeStudentActionPerformed

    private void logoutStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login object = new login();
        object.setVisible(true);
    }//GEN-LAST:event_logoutStudentActionPerformed

    private void aboutUsStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsStudentActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        aboutUS object = new aboutUS();
        object.setVisible(true);
    }//GEN-LAST:event_aboutUsStudentActionPerformed

    private void homeStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeStudent1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_homeStudent1ActionPerformed

    private void logoutStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutStudent1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        login object = new login();
        object.setVisible(true);
    }//GEN-LAST:event_logoutStudent1ActionPerformed

    private void aboutUsStudent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutUsStudent1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        aboutUS object = new aboutUS();
        object.setVisible(true);
    }//GEN-LAST:event_aboutUsStudent1ActionPerformed

    private void backShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backShowActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        home object = new home();
        object.setVisible(true);
    }//GEN-LAST:event_backShowActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new showStudent().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutUsStudent;
    private javax.swing.JMenuItem aboutUsStudent1;
    private javax.swing.JButton backShow;
    private javax.swing.JMenu editStudent;
    private javax.swing.JMenu editStudent1;
    private javax.swing.JMenu fileStudent;
    private javax.swing.JMenu fileStudent1;
    private javax.swing.JMenuItem homeStudent;
    private javax.swing.JMenuItem homeStudent1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenuItem logoutStudent;
    private javax.swing.JMenuItem logoutStudent1;
    // End of variables declaration//GEN-END:variables
}
